// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.emsi.tp_springgrpc.stubs;

public interface GetAllComptesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<ma.emsi.tp_springgrpc.stubs.Compte> 
      getComptesList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  ma.emsi.tp_springgrpc.stubs.Compte getComptes(int index);
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<? extends ma.emsi.tp_springgrpc.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  ma.emsi.tp_springgrpc.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
